name: CI

on:
  push:
    branches: [main, develop]
  pull_request:
    branches: [main, develop]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Bun
        uses: oven-sh/setup-bun@v2
        with:
          bun-version: latest

      - name: Install dependencies
        run: bun install

      - name: Check Biome formatting
        run: bun run format:check

      - name: Check Biome linting
        run: bun run lint:biome

      - name: Check ESLint
        run: bun run lint

      - name: Type check
        run: bunx tsc --noEmit

      - name: Build project
        run: bun run build

      - name: Run Biome check (format + lint)
        run: bun run check

  security:
    runs-on: ubuntu-latest
    needs: test

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Bun
        uses: oven-sh/setup-bun@v2
        with:
          bun-version: latest

      - name: Install dependencies
        run: bun install

      - name: Audit dependencies
        run: bun audit
